---
title: "Data Visualization with GGPlot"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages
```{r,message=FALSE}
library(leaflet)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(scales)
library(knitr)
```

## Load the data
```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        return(esc)
    }
)

head(esc)
```

## Annual counts by species and region 
```{r,message=FALSE}
annual_esc<-esc%>%
  separate(sampleDate,c("Year","Month","Day"))%>%
  mutate(Year=as.numeric(Year))%>%
  group_by(SASAP.Region,Species,Year)%>%
  summarise(escapemt=sum(DailyCount)) %>%
  filter(Species %in% c("Sockeye","Chum","Coho","Pink","Chinook"))
head(annual_esc)

```

## GGPLOT
```{r}
ggplot(annual_esc,mapping=aes(x=Species,y=escapemt,fill=SASAP.Region))+
  geom_col()
```

```{r}
annual_esc %>% 
  filter(SASAP.Region == "Kodiak") %>% 
ggplot(aes(x = Year, y = escapemt, color = Species)) + 
    geom_line() +
    geom_point()

kodiak_esc <- annual_esc %>% 
  filter(SASAP.Region == "Kodiak")

ggplot(kodiak_esc, aes(x = Year, y = escapemt, color = Species)) + 
    geom_line() +
    geom_point() +
    ylab("Escapement") +
    ggtitle("Kodiak Salmon Escapement") +
    theme_bw()
```

#TABLES
```{r}
locations<-esc %>%
  distinct(Location, Latitude,Longitude)%>%
drop_na()
```

```{r}
datatable(locations)
```

```{r}
kable(locations) #Generates a static table
```

## Interactive maps
```{r}
leaflet(locations) %>%
  addTiles() %>% #Default is open street map
  addMarkers(lng=~Longitude,lat=~Latitude,popup=~Location)
```

## More detailed interactive maps
```{r}
leaflet(locations) %>% 
  addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?",
              layers = 'GEBCO_LATEST',
              attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T,
                   weight = 0.5,
                   color = "white",
                   opacity = 1)
```

