---
title: "Maps"
author: "Kate Wilkins"
date: "11/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages for Mapping
```{r, message=FALSE}

library(sf)
library(dplyr)
library(ggplot2)
library(leaflet)
library(scales)
library(ggmap)

```

## Read in Map Data 
```{r}
ak_regions<-read_sf("shapefiles/ak_regions_simp.shp")
class(ak_regions)
head(ak_regions)
st_crs(ak_regions) #Provides projection information
```

## Plotting Data
```{r}
plot(ak_regions)
#Doesn't look correct, need to transform
```

## Transform Map Projection
```{r}
ak_regions_3338<- ak_regions %>%
    st_transform(crs = 3338)

plot(ak_regions_3338) #Plot looks much better!
```

## Read in Population Data
```{r}
pop <- read.csv("shapefiles/alaska_population.csv")

pop_4326<-st_as_sf(pop,
                  coords=c("lng","lat"), 
                  crs= 4326, #set this here according to what the data are 
                  #currently in, not what you want them to be in
                  remove=FALSE)
#head(pop_4326)

#Cannot join pop with ak until they have the same coordinate system

pop_3338<-pop_4326 %>% 
  st_transform(crs=3338)

pop_joined <- st_join(pop_3338, ak_regions_3338, join = st_within)

plot(pop_joined)

```

```{r,message=FALSE}
pop_region<-pop_joined %>%
  as.data.frame() %>%
  group_by(region) %>%
  summarise(total_pop=sum(population))

pop_region_3338<-left_join(ak_regions_3338,pop_region,by="region")

plot(pop_region_3338)
```

```{r}
pop_mgmt_338 <- pop_region_3338 %>% 
  group_by(mgmt_area) %>% 
  summarize(total_pop = sum(total_pop),do_union=FALSE) #do_union=FALSE maintains the regions delineated

plot(pop_mgmt_338)

```

```{r}
rivers_3338 <- read_sf("shapefiles/ak_rivers_simp.shp")
st_crs(rivers_3338)
```

## MAPS!

```{r}
ggplot()+
  geom_sf(data=pop_region_3338, mapping = aes(fill = total_pop)) +
   geom_sf(data = rivers_3338, aes(size = StrOrder), color = "black") +
  geom_sf(data=pop_3338,mapping=aes(),size=0.5)+
  scale_size(range=c(0.01,0.2),guide=FALSE)+
  theme_bw() +
  labs(fill = "Total Population") +
  scale_fill_continuous(low = "gray90", high =  "purple", labels = comma)
```

## Basemaps

```{r}
pop_3857 <- pop_3338 %>%
  st_transform(crs = 3857)

# Define a function to fix the bbox to be in EPSG:3857
# See https://github.com/dkahle/ggmap/issues/160#issuecomment-397055208
ggmap_bbox_to_3857 <- function(map) {
  if (!inherits(map, "ggmap")) stop("map must be a ggmap object")
  # Extract the bounding box (in lat/lon) from the ggmap to a numeric vector, 
  # and set the names to what sf::st_bbox expects:
  map_bbox <- setNames(unlist(attr(map, "bb")), 
                       c("ymin", "xmin", "ymax", "xmax"))
  
  # Coonvert the bbox to an sf polygon, transform it to 3857, 
  # and convert back to a bbox (convoluted, but it works)
  bbox_3857 <- st_bbox(st_transform(st_as_sfc(st_bbox(map_bbox, crs = 4326)), 3857))
  
  # Overwrite the bbox of the ggmap object with the transformed coordinates 
  attr(map, "bb")$ll.lat <- bbox_3857["ymin"]
  attr(map, "bb")$ll.lon <- bbox_3857["xmin"]
  attr(map, "bb")$ur.lat <- bbox_3857["ymax"]
  attr(map, "bb")$ur.lon <- bbox_3857["xmax"]
  map
}

```

```{r, message=FALSE}
bbox <- c(-170, 52, -130, 64)   # This is roughly southern Alaska
ak_map <- get_stamenmap(bbox, zoom = 4)
ak_map_3857 <- ggmap_bbox_to_3857(ak_map)
```

```{r}
ggmap(ak_map_3857) + 
  geom_sf(data = pop_3857, aes(color = population), inherit.aes = F) +
  scale_color_continuous(low = "gray90", high =  "purple", labels = comma)
```

## Leaflet Practice! 

```{r}
epsg3338 <- leaflet::leafletCRS(
  crsClass = "L.Proj.CRS",
  code = "EPSG:3338",
  proj4def =  "+proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",
  resolutions = 2^(16:7))
```

```{r}
pop_region_4326 <- pop_region_3338 %>% st_transform(crs = 4326)

```

```{r}
m <- leaflet(options = leafletOptions(crs = epsg3338)) %>%
        addPolygons(data = pop_region_4326, 
                    fillColor = "gray",
                    weight = 1)

pal <- colorNumeric(palette = "Reds", domain = pop_region_4326$total_pop)

m <- leaflet(options = leafletOptions(crs = epsg3338)) %>%
        addPolygons(data = pop_region_4326, 
                    fillColor = ~pal(total_pop),
                    weight = 1,
                    color = "black",
                    fillOpacity = 1,
                    label = ~region) %>% 
        addLegend(position = "bottomleft",
                  pal = pal,
                  values = range(pop_region_4326$total_pop),
                  title = "Total Population")
m
```

